services:
  postgres:
    image: postgres:17.5
    container_name: user_postgres
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  user-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: user_service
    restart: always
    ports:
      - '3000:3000'
      - '50051:50051'
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
      - ./certs:/app/certs:ro
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  redis:
    image: redis:7
    container_name: user_redis
    restart: always
    ports:
      - '6379:6379'
    command: ['redis-server', '--requirepass', '${REDIS_PASSWORD}']
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
