// @generated by protobuf-ts 2.11.1 with parameter client_grpc1,server_grpc1,use_proto_field_name
// @generated from protobuf file "proto/user/v1/user.proto" (package "proto.user.v1", syntax proto3)
// tslint:disable
import { UserService } from "./user";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { UpdateUserPlanResponse } from "./user";
import type { UpdateUserPlanRequest } from "./user";
import * as grpc from "@grpc/grpc-js";
/**
 * The UserService handles identity-related actions for internal service communication.
 *
 * @generated from protobuf service proto.user.v1.UserService
 */
export interface IUserServiceClient {
    /**
     * Updates the current plan associated with a user.
     *
     * Typically called by the PlanService when a user subscribes to,
     * upgrades, or cancels a plan.
     *
     * @generated from protobuf rpc: UpdateUserPlan
     */
    updateUserPlan(input: UpdateUserPlanRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: UpdateUserPlanResponse) => void): grpc.ClientUnaryCall;
    updateUserPlan(input: UpdateUserPlanRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: UpdateUserPlanResponse) => void): grpc.ClientUnaryCall;
    updateUserPlan(input: UpdateUserPlanRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: UpdateUserPlanResponse) => void): grpc.ClientUnaryCall;
    updateUserPlan(input: UpdateUserPlanRequest, callback: (err: grpc.ServiceError | null, value?: UpdateUserPlanResponse) => void): grpc.ClientUnaryCall;
}
/**
 * The UserService handles identity-related actions for internal service communication.
 *
 * @generated from protobuf service proto.user.v1.UserService
 */
export class UserServiceClient extends grpc.Client implements IUserServiceClient {
    private readonly _binaryOptions: Partial<BinaryReadOptions & BinaryWriteOptions>;
    constructor(address: string, credentials: grpc.ChannelCredentials, options: grpc.ClientOptions = {}, binaryOptions: Partial<BinaryReadOptions & BinaryWriteOptions> = {}) {
        super(address, credentials, options);
        this._binaryOptions = binaryOptions;
    }
    /**
     * Updates the current plan associated with a user.
     *
     * Typically called by the PlanService when a user subscribes to,
     * upgrades, or cancels a plan.
     *
     * @generated from protobuf rpc: UpdateUserPlan
     */
    updateUserPlan(input: UpdateUserPlanRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: UpdateUserPlanResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: UpdateUserPlanResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: UpdateUserPlanResponse) => void)): grpc.ClientUnaryCall {
        const method = UserService.methods[0];
        return this.makeUnaryRequest<UpdateUserPlanRequest, UpdateUserPlanResponse>(`/${UserService.typeName}/${method.name}`, (value: UpdateUserPlanRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): UpdateUserPlanResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
}
