// @generated by protobuf-ts 2.11.1 with parameter client_grpc1,server_grpc1,use_proto_field_name
// @generated from protobuf file "proto/user/v1/user.proto" (package "proto.user.v1", syntax proto3)
// tslint:disable
import { GetUserSettingsResponse } from "./user";
import { GetUserSettingsRequest } from "./user";
import { GetUserDetailsFromSessionResponse } from "./user";
import { GetUserDetailsFromSessionRequest } from "./user";
import { UpdateUserPlanResponse } from "./user";
import { UpdateUserPlanRequest } from "./user";
import type * as grpc from "@grpc/grpc-js";
/**
 * The UserService handles identity-related actions for internal service communication.
 *
 * @generated from protobuf service proto.user.v1.UserService
 */
export interface IUserService extends grpc.UntypedServiceImplementation {
    /**
     * Updates the current plan associated with a user.
     *
     * Typically called by the PlanService when a user subscribes to,
     * upgrades, or cancels a plan.
     *
     * @generated from protobuf rpc: UpdateUserPlan
     */
    updateUserPlan: grpc.handleUnaryCall<UpdateUserPlanRequest, UpdateUserPlanResponse>;
    /**
     * @generated from protobuf rpc: GetUserDetailsFromSession
     */
    getUserDetailsFromSession: grpc.handleUnaryCall<GetUserDetailsFromSessionRequest, GetUserDetailsFromSessionResponse>;
    /**
     * @generated from protobuf rpc: GetUserSettings
     */
    getUserSettings: grpc.handleUnaryCall<GetUserSettingsRequest, GetUserSettingsResponse>;
}
/**
 * @grpc/grpc-js definition for the protobuf service proto.user.v1.UserService.
 *
 * Usage: Implement the interface IUserService and add to a grpc server.
 *
 * ```typescript
 * const server = new grpc.Server();
 * const service: IUserService = ...
 * server.addService(userServiceDefinition, service);
 * ```
 */
export const userServiceDefinition: grpc.ServiceDefinition<IUserService> = {
    updateUserPlan: {
        path: "/proto.user.v1.UserService/UpdateUserPlan",
        originalName: "UpdateUserPlan",
        requestStream: false,
        responseStream: false,
        responseDeserialize: bytes => UpdateUserPlanResponse.fromBinary(bytes),
        requestDeserialize: bytes => UpdateUserPlanRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(UpdateUserPlanResponse.toBinary(value)),
        requestSerialize: value => Buffer.from(UpdateUserPlanRequest.toBinary(value))
    },
    getUserDetailsFromSession: {
        path: "/proto.user.v1.UserService/GetUserDetailsFromSession",
        originalName: "GetUserDetailsFromSession",
        requestStream: false,
        responseStream: false,
        responseDeserialize: bytes => GetUserDetailsFromSessionResponse.fromBinary(bytes),
        requestDeserialize: bytes => GetUserDetailsFromSessionRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(GetUserDetailsFromSessionResponse.toBinary(value)),
        requestSerialize: value => Buffer.from(GetUserDetailsFromSessionRequest.toBinary(value))
    },
    getUserSettings: {
        path: "/proto.user.v1.UserService/GetUserSettings",
        originalName: "GetUserSettings",
        requestStream: false,
        responseStream: false,
        responseDeserialize: bytes => GetUserSettingsResponse.fromBinary(bytes),
        requestDeserialize: bytes => GetUserSettingsRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(GetUserSettingsResponse.toBinary(value)),
        requestSerialize: value => Buffer.from(GetUserSettingsRequest.toBinary(value))
    }
};
